---
title: "Cobertura Vacinal"
author: "Raphael Saldanha"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width=12, fig.height=8)
```

## Pacotes

```{r}
library(tidyverse)
library(arrow)
library(lubridate)
library(hrbrthemes)
library(viridis)
```

## Dados

```{r}
tmp <- tempfile()
download.file(
  url = "https://raw.githubusercontent.com/wcota/covid19br/master/cases-brazil-states.csv", 
  destfile = tmp
)

read_csv_arrow(file = tmp, ) %>%
  write_parquet(sink = "cobertura.parquet")

unlink(tmp)

cobertura <- read_parquet(file = "cobertura.parquet")
```

## Brasil

```{r}
cobertura %>%
  filter(state == "TOTAL") %>%
  filter(date >= as.Date("2021-01-01")) %>%
  select(
    date, 
    vaccinated_per_100_inhabitants, 
    vaccinated_second_per_100_inhabitants, 
    vaccinated_third_per_100_inhabitants, 
    vaccinated_single_per_100_inhabitants
  ) %>%
  pivot_longer(!date) %>%
  mutate(name = case_when(
    name == "vaccinated_per_100_inhabitants" ~ "1a dose",
    name == "vaccinated_second_per_100_inhabitants" ~ "2a dose",
    name == "vaccinated_third_per_100_inhabitants" ~ "3a dose",
    name == "vaccinated_single_per_100_inhabitants" ~ "Dose única"
  )) %>%  
  ggplot(aes(x = date, y = value/100, color = name)) +
  geom_line(lwd = 1.3) +
  scale_y_continuous(labels = scales::label_percent(), limits = c(0,1)) +
  scale_x_date(date_breaks = "1 month",
             date_labels = "%m/%y") +
  theme_ipsum() +
  theme(legend.position = "bottom", legend.direction = "horizontal") +
  labs(title = "Percentual acumulado da população brasileira vacinada",
       subtitle = "segundo a dose", 
       caption = "Dados consolidados por W.Cota",
       color = "", y = "", x = "")
```


```{r}
cobertura %>%
  filter(state == "TOTAL") %>%
  filter(date >= as.Date("2021-01-01")) %>%
  filter(date <= as.Date("2022-02-01")) %>%
  select(
    date, 
    vaccinated_per_100_inhabitants, 
    vaccinated_second_per_100_inhabitants, 
    vaccinated_third_per_100_inhabitants, 
    vaccinated_single_per_100_inhabitants
  ) %>%
  pivot_longer(!date) %>%
  mutate(name = case_when(
    name == "vaccinated_per_100_inhabitants" ~ "1a dose",
    name == "vaccinated_second_per_100_inhabitants" ~ "2a dose",
    name == "vaccinated_third_per_100_inhabitants" ~ "3a dose",
    name == "vaccinated_single_per_100_inhabitants" ~ "Dose única"
  )) %>%
  ggplot(aes(x = date, y = value/100, color = name)) +
  geom_line(lwd = 1.3) +
  scale_y_continuous(labels = scales::label_percent(), limits = c(0,1)) +
  scale_x_date(date_breaks = "1 month",
             date_labels = "%m/%y") +
  theme_ipsum() +
  theme(legend.position = "bottom", legend.direction = "horizontal") +
  labs(title = "Percentual acumulado da população brasileira vacinada",
       subtitle = "segundo a dose (até 2022-03-01)", 
       caption = "Dados consolidados por W.Cota",
       color = "", y = "", x = "")
```



```{r}
res_03 <- read_parquet(file = "parquets/res_03.parquet")

res_03 %>%
  filter(nome_fabricante == "ASTRAZENECA/FIOCRUZ") %>%
  filter(data_aplicacao >= as.Date("2021-01-01")) %>%
  select(-nome_fabricante) %>%
  arrange(data_aplicacao) %>%
  mutate(doses_cum = cumsum(pessoas)) %>%
  ggplot(aes(x = data_aplicacao, y = doses_cum)) +
  geom_line(lwd = 1.3, color = "purple") +
  scale_y_continuous(labels = scales::label_comma()) +
  scale_x_date(date_breaks = "1 month",
             date_labels = "%m/%y") +
  theme_ipsum() +
  theme(legend.position = "bottom", legend.direction = "horizontal") +
  labs(title = "Quantidade acumulada de doses aplicadas",
       subtitle = "fabricadas pela AstraZeneca, por dia da aplicação", 
       caption = "Dados do SI-PNI",
       fill = "", y = "", x = "")
```


